/**
 * DATABASE CONSTANTS
 * 
 * This file is the single source of truth for all database table names, column names,
 * RPC function names, and Enums.
 * 
 * RULES FOR AI ASSISTANTS:
 * 1. NEVER hardcode string literals for table names (e.g. 'profiles'), columns, or RPCs.
 * 2. ALWAYS import and use these constants (e.g. TABLES.PROFILES, COLUMNS.PROFILES.ID).
 * 3. If a new table or column is added to the schema, update this file first.
 */

export const TABLES = {
  PROFILES: 'profiles',
  HOTSPOTS: 'hotspots',
  PLANS: 'plans',
  VOUCHERS: 'vouchers',
  SESSIONS: 'sessions',
  PURCHASES: 'purchases',
  TRANSACTIONS: 'transactions',
  CASHIN_REQUESTS: 'cashin_requests',
  KYC_SUBMISSIONS: 'kyc_submissions',
  PAYOUTS: 'payouts',
  SERVICE_REQUESTS: 'service_requests',
  HOST_EARNINGS: 'host_earnings',
  ADMIN_ACTIVITY_LOGS: 'admin_activity_logs',
  HOTSPOT_SECRETS: 'hotspot_secrets',
  PLATFORM_STATISTICS: 'platform_statistics',
  RATINGS: 'ratings',
  SYSTEM_SETTINGS: 'system_settings',
  TECHNICIAN_REQUESTS: 'technician_requests',
  USER_REPORTS: 'user_reports',
  NOTIFICATIONS: 'notifications',
} as const

export const RPC = {
  PROCESS_PURCHASE: 'process_purchase',
  NEARBY_HOTSPOTS: 'nearby_hotspots',
  PROCESS_CASHIN: 'process_cashin',
  REDEEM_VOUCHER: 'redeem_voucher',
  USER_CONFIRM_CASHIN: 'user_confirm_cashin',
  HOST_CREATE_CASHIN: 'host_create_cashin',
  HOST_COMPLETE_CASHIN: 'host_complete_cashin',
  REVEAL_HOTSPOT_SECRET: 'reveal_hotspot_secret',
  REFRESH_HOTSPOT_ONLINE_STATUS: 'refresh_hotspot_online_status',
  GET_HOST_DASHBOARD_STATS: 'get_host_dashboard_stats',
} as const

export const COLUMNS = {
  PROFILES: {
    ID: 'id',
    PHONE: 'phone',
    NAME: 'full_name',
    FULL_NAME: 'full_name',
    ROLE: 'role',
    WALLET_BALANCE: 'wallet_balance',
    KYC_STATUS: 'kyc_status',
    KYC_SUBMITTED_AT: 'kyc_submitted_at',
    KYC_REVIEWED_AT: 'kyc_reviewed_at',
    KYC_REVIEWER_NOTES: 'kyc_reviewer_notes',
    PROFILE_PHOTO_URL: 'profile_photo_url',
    LANGUAGE: 'language',
    IS_ACTIVE: 'is_active',
    LAST_LOGIN_AT: 'last_login_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  HOTSPOTS: {
    ID: 'id',
    HOST_ID: 'host_id',
    NAME: 'name',
    LANDMARK: 'landmark',
    ADDRESS: 'address',
    LAT: 'lat',
    LNG: 'lng',
    SSID: 'ssid',
    IS_ONLINE: 'is_online',
    SALES_PAUSED: 'sales_paused',
    HOURS: 'hours',
    ROUTER_MODEL: 'router_model',
    ROUTER_SERIAL: 'router_serial',
    LOCATION: 'location',
    RANGE_METERS: 'range_meters',
    WIFI_RANGE_METERS: 'wifi_range_meters',
    LAST_SEEN_AT: 'last_seen_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PLANS: {
    ID: 'id',
    HOTSPOT_ID: 'hotspot_id',
    NAME: 'name',
    DURATION_SECONDS: 'duration_s',
    DATA_BYTES: 'data_cap_bytes',
    PRICE_XOF: 'price_xof',
    IS_ACTIVE: 'is_active',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  VOUCHERS: {
    ID: 'id',
    CODE: 'code',
    USER_ID: 'user_id',
    HOTSPOT_ID: 'hotspot_id',
    PLAN_ID: 'plan_id',
    PURCHASE_ID: 'purchase_id',
    EXPIRES_AT: 'expires_at',
    USED_AT: 'used_at',
    DEVICE_MAC: 'device_mac',
    CREATED_AT: 'created_at',
  },
  SESSIONS: {
    ID: 'id',
    VOUCHER_ID: 'voucher_id',
    DEVICE_MAC: 'device_mac',
    STARTED_AT: 'started_at',
    ENDED_AT: 'ended_at',
    DATA_USED: 'data_used',
    LAST_ACTIVITY_AT: 'last_activity_at',
  },
  PURCHASES: {
    ID: 'id',
    USER_ID: 'user_id',
    HOTSPOT_ID: 'hotspot_id',
    PLAN_ID: 'plan_id',
    VOUCHER_ID: 'voucher_id',
    AMOUNT: 'amount_xof',
    PAYMENT_PROVIDER: 'provider',
    PAYMENT_STATUS: 'status',
    PAYMENT_REFERENCE: 'payment_reference',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRANSACTIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    TYPE: 'type',
    AMOUNT: 'amount',
    BALANCE_BEFORE: 'balance_before',
    BALANCE_AFTER: 'balance_after',
    REFERENCE_ID: 'reference_id',
    REFERENCE_TYPE: 'reference_type',
    DESCRIPTION: 'description',
    METADATA: 'metadata',
    CREATED_AT: 'created_at',
  },
  CASHIN_REQUESTS: {
    ID: 'id',
    HOST_ID: 'host_id',
    USER_ID: 'user_id',
    USER_PHONE: 'user_phone',
    AMOUNT: 'amount',
    COMMISSION: 'commission',
    STATUS: 'status',
    QR_CODE: 'qr_code',
    EXPIRES_AT: 'expires_at',
    CREATED_AT: 'created_at',
    CONFIRMED_AT: 'confirmed_at',
    REJECTED_AT: 'rejected_at',
    REJECTION_REASON: 'rejection_reason',
  },
  KYC_SUBMISSIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    FULL_NAME: 'full_name',
    ID_TYPE: 'id_type',
    ID_NUMBER: 'id_number',
    ID_PHOTO_URL: 'id_photo_url',
    ID_CARD_URL: 'id_photo_url', // alias for backward compatibility
    SELFIE_PHOTO_URL: 'selfie_photo_url',
    SELFIE_URL: 'selfie_photo_url', // alias for backward compatibility
    ADDRESS: 'address',
    CITY: 'city',
    COUNTRY: 'country',
    DATE_OF_BIRTH: 'date_of_birth',
    BUSINESS_NAME: 'business_name',
    BUSINESS_REGISTRATION: 'business_registration',
    STATUS: 'status',
    SUBMITTED_AT: 'submitted_at',
    REVIEWED_AT: 'reviewed_at',
    REVIEWED_BY: 'reviewed_by',
    REVIEWER_NOTES: 'reviewer_notes',
  },
  PAYOUTS: {
    ID: 'id',
    HOST_ID: 'host_id',
    AMOUNT: 'amount_xof',
    FEE: 'fee',
    NET_AMOUNT: 'net_amount',
    PAYMENT_PROVIDER: 'payment_provider',
    PAYMENT_ACCOUNT: 'payment_account',
    STATUS: 'status',
    REFERENCE: 'reference',
    REQUESTED_AT: 'requested_at',
    PROCESSED_AT: 'processed_at',
    COMPLETED_AT: 'completed_at',
    FAILED_AT: 'failed_at',
    FAILURE_REASON: 'failure_reason',
    CANCELLED_AT: 'cancelled_at',
    CANCELLATION_REASON: 'cancellation_reason',
  },
  SERVICE_REQUESTS: {
    ID: 'id',
    HOST_ID: 'host_id',
    HOTSPOT_ID: 'hotspot_id',
    TECHNICIAN_ID: 'technician_id',
    TYPE: 'type',
    PRIORITY: 'priority',
    STATUS: 'status',
    TITLE: 'title',
    DESCRIPTION: 'description',
    LOCATION: 'location',
    PHOTOS: 'photos',
    NOTES: 'notes',
    RESOLUTION: 'resolution',
    RATING: 'rating',
    CREATED_AT: 'created_at',
    ASSIGNED_AT: 'assigned_at',
    STARTED_AT: 'started_at',
    COMPLETED_AT: 'completed_at',
    CANCELLED_AT: 'cancelled_at',
    CANCELLATION_REASON: 'cancellation_reason',
    UPDATED_AT: 'updated_at',
  },
  HOST_EARNINGS: {
    ID: 'id',
    HOST_ID: 'host_id',
    PERIOD_START: 'period_start',
    PERIOD_END: 'period_end',
    TOTAL_SALES: 'total_sales',
    PLATFORM_FEE: 'platform_fee',
    CASHIN_COMMISSION: 'cashin_commission',
    NET_EARNINGS: 'net_earnings',
    PURCHASES_COUNT: 'purchases_count',
    CASHIN_COUNT: 'cashin_count',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ADMIN_ACTIVITY_LOGS: {
    ID: 'id',
    ADMIN_ID: 'admin_id',
    ACTION: 'action',
    DETAILS: 'details',
    CREATED_AT: 'created_at',
  },
  HOTSPOT_SECRETS: {
    ID: 'id',
    HOTSPOT_ID: 'hotspot_id',
    SECRET: 'secret',
    CREATED_AT: 'created_at',
  },
  PLATFORM_STATISTICS: {
    ID: 'id',
    STAT_DATE: 'stat_date',
    TOTAL_USERS: 'total_users',
    NEW_USERS_TODAY: 'new_users_today',
    TOTAL_HOSTS: 'total_hosts',
    NEW_HOSTS_TODAY: 'new_hosts_today',
    TOTAL_HOTSPOTS: 'total_hotspots',
    ACTIVE_HOTSPOTS: 'active_hotspots',
    TOTAL_REVENUE: 'total_revenue',
    PLATFORM_REVENUE: 'platform_revenue',
    TOTAL_PURCHASES: 'total_purchases',
    TOTAL_SESSIONS: 'total_sessions',
    AVG_SESSION_DURATION: 'avg_session_duration',
    PENDING_KYC: 'pending_kyc',
    PENDING_PAYOUTS: 'pending_payouts',
    ERROR_COUNT: 'error_count',
    UPTIME_PERCENTAGE: 'uptime_percentage',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  RATINGS: {
    ID: 'id',
    USER_ID: 'user_id',
    HOTSPOT_ID: 'hotspot_id',
    RATING: 'rating',
    COMMENT: 'comment',
    CREATED_AT: 'created_at',
  },
  SYSTEM_SETTINGS: {
    ID: 'id',
    KEY: 'key',
    VALUE: 'value',
    DESCRIPTION: 'description',
  },
  TECHNICIAN_REQUESTS: {
    ID: 'id',
    HOST_ID: 'host_id',
    HOTSPOT_ID: 'hotspot_id',
    TECHNICIAN_ID: 'technician_id',
    SUBJECT: 'subject',
    DESCRIPTION: 'description',
    PRIORITY: 'priority',
    STATUS: 'status',
    PHOTO_URL: 'photo_url',
    REJECTION_REASON: 'rejection_reason',
    COMPLETION_NOTES: 'completion_notes',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    ASSIGNED_AT: 'assigned_at',
    ACCEPTED_AT: 'accepted_at',
    COMPLETED_AT: 'completed_at',
  },
  USER_REPORTS: {
    ID: 'id',
    USER_ID: 'user_id',
    REPORT_TYPE: 'report_type',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
  },
  NOTIFICATIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    TYPE: 'type',
    TITLE: 'title',
    MESSAGE: 'message',
    ACTION_URL: 'action_url',
    REFERENCE_ID: 'reference_id',
    REFERENCE_TYPE: 'reference_type',
    METADATA: 'metadata',
    IS_READ: 'is_read',
    READ_AT: 'read_at',
    CREATED_AT: 'created_at',
  },
} as const

export const ENUMS = {
  USER_ROLE: {
    GUEST: 'guest',
    USER: 'user',
    HOST: 'host',
    TECHNICIAN: 'technician',
    ADMIN: 'admin',
  },
  PAYMENT_PROVIDER: {
    WAVE: 'wave',
    ORANGE: 'orange',
    MOOV: 'moov',
    WALLET: 'wallet',
  },
  PAYMENT_STATUS: {
    PENDING: 'pending',
    SUCCESS: 'success',
    CONFIRMED: 'confirmed',
    FAILED: 'failed',
    EXPIRED: 'expired',
  },
  HOTSPOT_STATUS: {
    ONLINE: 'online',
    OFFLINE: 'offline',
  },
  KYC_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  CASHIN_STATUS: {
    PENDING: 'pending',
    CONFIRMED: 'confirmed',
    EXPIRED: 'expired',
    REJECTED: 'rejected',
  },
  SERVICE_REQUEST_TYPE: {
    ROUTER_ISSUE: 'router-issue',
    SETUP_HELP: 'setup-help',
    NETWORK_PROBLEM: 'network-problem',
    MAINTENANCE: 'maintenance',
    HARDWARE_REPAIR: 'hardware-repair',
    OTHER: 'other',
  },
  SERVICE_REQUEST_PRIORITY: {
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    URGENT: 'urgent',
  },
  SERVICE_REQUEST_STATUS: {
    PENDING: 'pending',
    ASSIGNED: 'assigned',
    IN_PROGRESS: 'in-progress',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
  },
  TRANSACTION_TYPE: {
    PURCHASE: 'purchase',
    TOPUP: 'topup',
    CASHIN_COMMISSION: 'cashin_commission',
    SALES_REVENUE: 'sales_revenue',
    PAYOUT: 'payout',
    REFUND: 'refund',
  },
  PAYOUT_STATUS: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
  },
} as const

export type PaymentStatus = typeof ENUMS.PAYMENT_STATUS[keyof typeof ENUMS.PAYMENT_STATUS]
export type CashInStatus = typeof ENUMS.CASHIN_STATUS[keyof typeof ENUMS.CASHIN_STATUS]
export type HotspotStatus = typeof ENUMS.HOTSPOT_STATUS[keyof typeof ENUMS.HOTSPOT_STATUS]
export type PayoutStatus = typeof ENUMS.PAYOUT_STATUS[keyof typeof ENUMS.PAYOUT_STATUS]
export type KycStatus = typeof ENUMS.KYC_STATUS[keyof typeof ENUMS.KYC_STATUS]

export const PAYMENT_STATUS_SUCCESS: PaymentStatus[] = [
  ENUMS.PAYMENT_STATUS.SUCCESS,
  ENUMS.PAYMENT_STATUS.CONFIRMED,
]
